
spring.application.name=backendAssignment
server.port=8080

ratelimiting.requestperminute=60

spring.datasource.url=jdbc:postgresql://dpg-d78gbuvfte5s73929e0g-a.oregon-postgres.render.com:5432/mydb_devf
spring.datasource.username=myuser
spring.datasource.password=kjpinmd272LlJlSH3zdfH51xJH3hP5mo

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

jwt.secretKey=dvdvdfkwfewbgfewjofjwrpgohwerufghepofeofquedfviqyf



logging.level.org.springframework.security=INFO

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
